let data = [
  {
    id: 1,
    brandImage: "./images/Group 346.svg",
    category: "Men",
    image: "./dynamic/Group 1441@2x.png",
    gallery: [
      "./dynamic/Group 329@2x.png",
      "./dynamic/Group 331@2x.png",
      "./dynamic/Group 333@2x.png",
      "./dynamic/Group 335@2x.png",
    ],
    description:
      "Adidas black t-shirt lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    price: "9,999",
    currency: "LE",
    discount: "30%",
    size: ["Small", "Medium", "Large", "X Large", "XX Large"],
    color: ["./dynamic/Group 354.png", "./dynamic/Group 356.png"],
    rate: 4.9,
    maxRate: 5,
    votes: "22 Rates",
    stars: 4,
    from: "",
    to: "",
    in: "",
    360: true,
  },
  {
    id: 2,
    brandImage: "./images/Group 346.svg",
    category: "Women",
    image: "./dynamic/Group 575@2x.png",
    gallery: ["./dynamic/Group 575.png"],
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    price: "9,999 LE",
    currency: "LE",
    discount: "50%",
    size: ["Small", "Medium", "Large", "X Large", "XX Large"],
    color: [],
    rate: 4.2,
    maxRate: 5,
    votes: "22 Rates",
    stars: 4,
    from: "Genena Mall",
    to: "",
    in: "",
    360: true,
  },
  {
    id: 3,
    brandImage: "./images/Group 346.svg",
    category: "Men",
    image: "./dynamic/Group 583@2x.png",
    gallery: ["./dynamic/Group 583.png"],
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    price: "9,999 LE",
    currency: "LE",
    discount: "",
    size: ["Small", "Medium", "Large", "X Large", "XX Large"],
    color: [],
    rate: 4.2,
    maxRate: 5,
    votes: "22 Rates",
    stars: 4,
    from: "UK",
    to: "Egypt",
    in: "10",
    360: true,
  },
  {
    id: 4,
    brandImage: "./images/Group 346.svg",
    category: "Men",
    image: "./dynamic/Group 589@2x.png",
    gallery: ["./dynamic/Group 589.png"],
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    price: "9,999",
    currency: "LE",
    discount: "30%",
    size: ["Small", "Medium", "Large", "X Large", "XX Large"],
    color: [],
    rate: 4.2,
    maxRate: 5,
    votes: "22 Rates",
    stars: 4,
    from: "Genena Mall",
    to: "",
    in: "",
    360: true,
  },
  {
    id: 5,
    brandImage: "./images/Group 346.svg",
    category: "Men",
    image: "./dynamic/Group 597@2x.png",
    gallery: ["./dynamic/Group 597.png"],
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    price: "9,999 LE",
    currency: "LE",
    discount: "70%",
    size: ["Small", "Medium", "Large", "X Large", "XX Large"],
    color: [""],
    rate: 4.2,
    maxRate: 5,
    votes: "22 Rates",
    stars: 4,
    from: "Egypt",
    to: "Egypt",
    in: "10",
    360: true,
  },
];

export function getData() {
  return new Promise((res, rej) => {
    setTimeout(() => res(data), 1000);
  });
}
